### ISSUE TITLE
Next pypi release?

### ISSUE THREAD

**Issue by Trii** [wtforms/wtforms-appengine#22]
When are you making the next pypi release? I'm looking forward to the `query=` option for `KeyPropertyField` for use in a current project.

**Comment by mikelambert** [comment]
@trii , you're familiar with how to use pip to install packages off of github, right?
pip install git+http://www.github.com/wtforms/wtforms-appengine

@crast , I think pypi releases are still in your court, right?

**Comment by Trii** [comment]
@mikelambert as of now, `pip install` is only installing the top level of the package. I've corrected it so that it will install: https://github.com/Trii/wtforms-appengine/commit/b9e5fa537be4e83826405c0df52318e189818297

**Comment by Trii** [comment]
I thought so too but it did not work on my system using `pip install git+http...`

```
Python 2.7.10 (default, Oct 23 2015, 18:05:06)
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
```

**Comment by mikelambert** [comment]
Python 2.7.10 (default, Aug 22 2015, 20:33:39) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)] on darwin

And pip install git+http://www.github.com/wtforms/wtforms-appengine correctly installs the fields/ subdirectory for me. Are you perhaps forgetting to run with --upgrade and still seeing an older version installed on disk?

Regardless, if you want to submit a pull request, I'm happy to merge in your change to use find_packages, as I agree it's better. Just not sure how it will materially affect anything for you. :)

**Comment by Trii** [comment]
I had originally installed it from pypi and it included the `.fields` module. I found the error when I changed my requirements.txt to use `pip install git+http://www.github.com/wtforms/wtforms-appengine`. Must have been user error!

More specifically `pip install -U -t src/lib -r requirements.txt`

**Comment by ericvader** [comment]
Looking forward to the next pypi release! Bump!
